protected/controllers/PageController.php
<?php

class PageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	//public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			/*array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),*/
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update','view','im'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView( $id, $type )
	{

		if ( empty( $type ) || empty( $id ) )
				{
					throw new CHttpException( 404, 'The requested page does not exist.' );
				}

		$user_id = Yii::app()->user->getId();
		switch ( $type ) {
			case 'group':

				$user = Users::model()->withGroup()->findByPk( $user_id );
				if ( !( ( !empty( $user->groups->id ) ) && $user->groups->id == $id ) )
					throw new CHttpException( 404, 'The requested page does not exist.' );
				$model = Groups::model()->findByAttributes( array( 'id' => $id ) );

				break;
			case 'special':

				$user = Users::model()->withSpecial()->findByPk( $user_id );
				if ( !( ( !empty( $user->groups->special->id ) ) && $user->groups->special->id == $id ) )
					throw new CHttpException( 404, 'The requested page does not exist.' );
				$model = Special::model()->findByAttributes( array( 'id' => $id ) );

				break;
			case 'faculty':

				$user = Users::model()->withFaculty()->findByPk( $user_id );
				if ( !( ( !empty( $user->groups->special->faculty->id ) ) && $user->groups->special->faculty->id == $id ) )
					throw new CHttpException( 404, 'The requested page does not exist.' );
				$model = Faculty::model()->findByAttributes( array( 'id' => $id ) );

				break;
		}

		if ( empty( $model ) )
			throw new CHttpException( 404, 'The requested page does not exist.' );

		$page = $model->pages;

		$messages = $model->pages->messages(
			array(
			     'order' => 'id DESC',
			     'limit' => 10,
			)
		);

		sort( $messages );

		$massageForm = new Message;
		$this->render(
			'view',
			array(
			     'model'       => $model,
			     'type'        => $type,
			     'massageForm' => $massageForm,
			     'messages'    => $messages,
			     'page'        => $page,
			)
		);
	}

	/**
	 * Chat.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionIm($to)
	{
		$user_id = Yii::app()->user->getId();
		$messages = Yii::app()->db->createCommand()
			->select('t.* , u.user_name')
			->leftJoin('users u', 't.users_id=u.id')
			->from('message t')
			->where('( t.users_id=:user_id and t.to_user=:to_user ) or ( t.users_id=:to_user and t.to_user=:user_id )', array(':user_id'=>$user_id, ':to_user'=>$to))
			->limit(10)
			->order('t.id desc')
			->queryAll();

		sort($messages);

		$massageForm = new Message;
		$this->renderPartial(
			'_im',
			array(
			     'massageForm' => $massageForm,
			     'messages'    => $messages,
			     'to_user' => $to,
			)
		);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	/*public function actionCreate()
	{
		$model=new Pages;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pages']))
		{
			$model->attributes=$_POST['Pages'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}*/

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	/*public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Pages']))
		{
			$model->attributes=$_POST['Pages'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}*/

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	/*public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}*/

	/**
	 * Lists all models.
	 */
	/*public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Pages');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}*/

	/**
	 * Manages all models.
	 */
	/*public function actionAdmin()
	{
		$model=new Pages('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Pages']))
			$model->attributes=$_GET['Pages'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}*/

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	/*public function loadModel($id)
	{
		$model=Pages::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}*/

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	/*protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='pages-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}*/
}

protected/views/page/_im.php
<?php
/* @var $this PageController */
/* @var $model Pages */


/*$this->menu=array(
	array('label'=>'List Pages', 'url'=>array('index')),
	array('label'=>'Create Pages', 'url'=>array('create')),
	array('label'=>'Update Pages', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Pages', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Pages', 'url'=>array('admin')),
);*/
?>

<div>
    <div class="b-modal" id="exampleModal">
        <div class="b-modal_close arcticmodal-close">X</div>

<div class="">
    <div class="row-fluid show-grid">
        <div id="im" class="span10" style="height: 300px; overflow: auto; border: 1px solid;">
			<?php
			if ( !empty( $messages ) ) {
				foreach ( $messages as $message ) {
					$this->renderPartial(
						'//message/_messageIm',
						array(
						     'message'=>$message,
						)
					);
				}
			}
			?>
            <!--Body content-->
        </div>
    </div>
    <div class="row-fluid show-grid">
        <div class="span7 offset2">
            <!--Massages content-->
			<?php
			$form = $this->beginWidget(
				'CActiveForm',
				array(
				     'id'                   => 'massage-form',
				     'action'               =>  array('message/get', 'to_user'=>$to_user ),
				     /*'enableAjaxValidation' => true,*/
				     'htmlOptions'          => array(
					     'class' => 'form-horizontal',
					     //'onSubmit' => 'return true;',
				     ),
				     /*'clientOptions'        => array(
					 'validateOnSubmit' => true,
					 'validateOnChange' => true,
				 ),*/
				)
			);
			?>

            <fieldset>
                <div class="show-grid">
                    <img src="js/holder.js/50x50/#c0f2a7:#99c185" class="img-rounded">
					<?php
					echo $form->textArea(
						$massageForm,
						'text',
						array(
						     'rows'        => 2,
						     'cols'        => 60,
						     'placeholder' => $massageForm->getAttributeLabel( 'text' ),
						     'onkeyup'=> 'EDU.enableButtonMessages(this);',
						)
					);
					?>
					<?php
					echo CHtml::submitButton(
						'Create',
						array(
						     'class'   => 'btn btn-small btn-primary',
						     'onclick' => 'return EDU.sendMassageIm("' . $this->createUrl( 'user/view' ) . '","#sdasd", this);',
						     'disabled' => 'disabled',
						)
					);
					?>
                </div>
            </fieldset>



			<?php $this->endWidget(); ?>

        </div>
    </div>
</div>


    </div>
</div>

protected/views/page/_user.php
<?php foreach ( $users as $user ): if ($user->id === Yii::app()->user->getId()) continue; ?>
<dl>
    <dt></dt>
    <dd>
        <img src="js/holder.js/50x50/#c0f2a7:#99c185" class="img-rounded">
		<?php echo $user->user_name; ?>
        <span class="m-dotted" onclick="EDU.im('<?php echo $this->createUrl( 'page/im', array('to'=>$user->id) ); ?>',this );">+</span>
    </dd>
</dl>
<?php endforeach;?>

protected/views/page/_users.php
<?php if ($type == 'group' && !empty( $model->users )):?>
	<?php
		$this->renderPartial(
			'_user',
			array(
			     'users' => $model->users,
			)
		);
		?>

<?php elseif ( $type == 'special' && !empty( $model->groups ) ):?>
	<div class="accordion" id="accordion2">
	<?php foreach ( $model->groups as $group ): if (empty($group->users)) continue;  ?>
		<div class="accordion-group">
	        <div class="accordion-heading">
	            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse<?php echo $group->id; ?>">
		            <?php echo $group->name; ?>
	            </a>
	        </div>
		<div id="collapse<?php echo $group->id; ?>" class="accordion-body collapse">
            <div class="accordion-inner">
			<?php
			$this->renderPartial(
				'_user',
				array(
				     'users' => $group->users,
				)
			);
			?>
            </div>
        </div>
       </div>
	<?php endforeach;?>
    </div>
<?php elseif ( $type == 'faculty' && !empty( $model->specials ) ): ?>
<div class="accordion" id="accordion2">
	<?php foreach ( $model->specials as $special ): if (empty($special->groups)) continue;  ?>
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapses<?php echo $special->id; ?>">
				<?php echo $special->name; ?>
            </a>
        </div>
        <div id="collapses<?php echo $special->id; ?>" class="accordion-body collapse">
            <div class="accordion-inner">
				<?php foreach ( $special->groups as $group ): if (empty($group->users)) continue; ?>
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#collapses<?php echo $special->id; ?>" href="#collapseg<?php echo $group->id; ?>">
				            <?php echo $group->name; ?>
                        </a>
                    </div>
                    <div id="collapseg<?php echo $group->id; ?>" class="accordion-body collapse">
                        <div class="accordion-inner">
		            <?php
		            $this->renderPartial(
			            '_user',
			            array(
			                 'users' => $group->users,
			            )
		            );
		            ?>
                        </div>
                    </div>
                </div>
				<?php endforeach;?>
            </div>
        </div>
    </div>
	<?php endforeach;?>
</div>
<?php endif; ?>

protected/views/page/_view.php
<?php
/* @var $this PageController */
/* @var $data Pages */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b>
	<?php echo CHtml::encode($data->description); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('create_time')); ?>:</b>
	<?php echo CHtml::encode($data->create_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('update_time')); ?>:</b>
	<?php echo CHtml::encode($data->update_time); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('captain_id')); ?>:</b>
	<?php echo CHtml::encode($data->captain_id); ?>
	<br />


</div>

protected/views/page/index.php
<?php
/* @var $this PageController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Pages',
);

$this->menu=array(
	array('label'=>'Create Pages', 'url'=>array('create')),
	array('label'=>'Manage Pages', 'url'=>array('admin')),
);
?>

<h1>Pages</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/page/view.php
<?php
/* @var $this PageController */
/* @var $model Pages */

$this->breadcrumbs=array(
	'Pages'=>array('index'),
	$model->name,
);

/*$this->menu=array(
	array('label'=>'List Pages', 'url'=>array('index')),
	array('label'=>'Create Pages', 'url'=>array('create')),
	array('label'=>'Update Pages', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Pages', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Pages', 'url'=>array('admin')),
);*/
?>

<h1>View Pages #<?php echo $model->name; ?></h1>

<?php /*$this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'description',
		'create_time',
		'update_time',
		'captain_id',
	),
)); */?>

<div class="">
    <div class="row-fluid show-grid">
        <div class="span4">
	        <?php
	        $this->renderPartial(
		        '_users',
		        array(
		             'model'=>$model,
		             'type'=>$type,
		        )
	        );
	        ?>
            <!--Sidebar content-->
        </div>
        <div class="span8" style="height: 300px; overflow: auto; border: 1px solid;">
	        <?php
	        if ( !empty( $messages ) ) {
		        foreach ( $messages as $message ) {
			        $this->renderPartial(
				        '//message/_message',
				        array(
				             'message'=>$message,
				        )
			        );
		        }
	        }
			?>
            <!--Body content-->
        </div>
    </div>
    <div class="row-fluid show-grid">
        <div class="span7 offset2">
            <!--Massages content-->
	        <?php
	        $form = $this->beginWidget(
		        'CActiveForm',
		        array(
		             'id'                   => 'massage-form',
		             'action'               =>  array('message/get', 'type' => $type, 'id' => $model->id, 'page'=>$page->id ),
		             /*'enableAjaxValidation' => true,*/
		             'htmlOptions'          => array(
			             'class' => 'form-horizontal',
			             //'onSubmit' => 'return true;',
		             ),
		             /*'clientOptions'        => array(
			             'validateOnSubmit' => true,
			             'validateOnChange' => true,
		             ),*/
		        )
	        );
	        ?>

            <fieldset>
                <div class="show-grid">
                <img src="js/holder.js/50x50/#c0f2a7:#99c185" class="img-rounded">
	            <?php
	            echo $form->textArea(
		            $massageForm,
		            'text',
		            array(
		                 'rows'        => 2,
		                 'cols'        => 60,
		                 'placeholder' => $model->getAttributeLabel( 'text' ),
		                 'onkeyup'=> 'EDU.enableButtonMessages(this);',
		            )
	            );
	            ?>
	            <?php
	            echo CHtml::submitButton(
		            'Create',
		            array(
		                 'class'   => 'btn btn-small btn-primary',
		                 'onclick' => 'return EDU.sendMassage("' . $this->createUrl( 'user/view' ) . '","#sdasd", this);',
		                 'disabled' => 'disabled',
		            )
	            );
	            ?>
                </div>
            </fieldset>



	        <?php $this->endWidget(); ?>

        </div>
    </div>
</div>